version: "3.6"
services:
  elastic:
    image: bakingbad/bcdhub-elastic:${TAG} #ghcr.io/baking-bad/bcdhub-elastic:${TAG}
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    logging: &bcd-logging
      options:
        max-size: 10m
        max-file: "5"

  db:
    image: postgres:12
    shm_size: 1g
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=indexer
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    logging: *bcd-logging

  api:
    restart: always
    image: bakingbad/bcdhub-api:${TAG} #ghcr.io/baking-bad/bcdhub-api:${TAG}
    environment:
      - BCD_ENV=sandbox
      - GIN_MODE=debug
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SANDBOX_NODE_URI=http://sandbox:20000
      - SANDBOX_IPFS_GATEWAY=http://localipfs:8080
    depends_on:
      - elastic
      - db
    ports:
      - 14000:14000
    expose:
      - 14000/tcp
    volumes:
      - bcdshare:/etc/bcd
    links:
      - "flextesa:sandbox"
      - "ipfs:localipfs"
    logging: *bcd-logging

  indexer:
    restart: always
    image: bakingbad/bcdhub-indexer:${TAG} #ghcr.io/baking-bad/bcdhub-indexer:${TAG}
    environment:
      - BCD_ENV=sandbox
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SANDBOX_NODE_URI=http://sandbox:20000
      - SANDBOX_IPFS_GATEWAY=http://localipfs:8080
    depends_on:
      - db
      - metrics
    links:
      - "flextesa:sandbox"
      - "ipfs:localipfs"
    volumes:
      - bcdshare:/etc/bcd
    logging: *bcd-logging

  metrics:
    restart: always
    image: bakingbad/bcdhub-metrics:${TAG} #ghcr.io/baking-bad/bcdhub-metrics:${TAG}
    environment:
      - BCD_ENV=sandbox
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SANDBOX_NODE_URI=http://sandbox:20000
      - SANDBOX_IPFS_GATEWAY=http://localipfs:8080
    depends_on:
      - elastic
      - db
    links:
      - "flextesa:sandbox"
      - "ipfs:localipfs"
    volumes:
      - bcdshare:/etc/bcd
    logging: *bcd-logging

  gui:
    container_name: sandbox-gui
    restart: always
    image: bakingbad/bcdhub-gui:4.0 #ghcr.io/baking-bad/bcdhub-gui:${TAG}
    depends_on:
      - api
    ports:
      - 127.0.0.1:8000:80
    logging: *bcd-logging

  #
  # Flextesa
  #
  flextesa:
    restart: always
    image: oxheadalpha/flextesa:20220127  # prev: 20211207 #20211119 with hangzhou # 20210602 granada
    command: hangzbox start
    environment:
      - block_time=10
      - flextesa_node_cors_origin=*
    ports:
      - "20000:20000"
    expose:
      - 20000/tcp
    logging: &flextesa-logging
      options:
        max-size: 10m
        max-file: "5"

  #
  # IPFS
  #
  ipfs:
    container_name: ipfs-node
    restart: always
    image: ipfs/go-ipfs:latest
    #bootstrap rm --all
    #command: bootstrap add /ip4/127.0.0.1/tcp/4001/ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc
    environment:
      #- IPFS_SWARM_KEY=/key/swarm/psk/1.0.0/\n/base16/\n925e93e58f6cb4aa7a5660e5166a3081f84d40a6888f70d49fdbc68f0f10362a
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./ipfsdata:/ipfsdata
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "5001:5001"
      - "8080:8080"
      - "8081:8081"
    expose:
      - 4001/tcp
      - 4001/udp
      - 5001/tcp
      - 8080/tcp
      - 8081/tcp
    logging: &ipfs-logging
      options:
        max-size: 10m
        max-file: "5"

  #
  # tzkt api
  #
  db-tzkt:
    container_name: db-tzkt
    restart: always
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tzkt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
      POSTGRES_DB: ${POSTGRES_DB:-tzkt_db}
      PGPORT: 15432
    volumes:
      - db-tzkt:/var/lib/postgresql/data
    expose:
      - 15432
    ports:
      - 15432:15432
    logging: &tzkt-logging
      options:
        max-size: 10m
        max-file: "5"

  api-tzkt:
    container_name: api-tzkt
    restart: always
    image: bakingbad/tzkt-api:latest
    depends_on:
      - db-tzkt
      - flextesa
    environment:
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
      ConnectionStrings__DefaultConnection: host=db-tzkt;port=15432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};
    expose:
      - 5000
    ports:
      - 0.0.0.0:5020:5000
    logging: *tzkt-logging

  sync-tzkt:
    container_name: sync-tzkt
    restart: always
    image: bakingbad/tzkt-sync:latest
    environment:
      TezosNode__Endpoint: http://sandbox:20000
      ConnectionStrings__DefaultConnection: host=db-tzkt;port=15432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};
    links:
      - "flextesa:sandbox"
    depends_on:
      - db-tzkt
      - flextesa
    logging: *tzkt-logging

volumes:
  esdata:
  bcdshare:
  db:
    driver: local
  db-tzkt:
    driver: local