version: "3.6"
services:
  elastic:
    image: bakingbad/bcdhub-elastic:4.0
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    logging: &bcd-logging
      options:
        max-size: 10m
        max-file: "5"

  db:
    image: postgres:12
    shm_size: 1g
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=indexer
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    logging: *bcd-logging

  api:
    restart: always
    image: bakingbad/bcdhub-api:4.0
    environment:
      - BCD_ENV=sandbox
      - GIN_MODE=debug
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SANDBOX_NODE_URI=http://sandbox:20000
      - SANDBOX_IPFS_GATEWAY=http://localipfs:8080
    depends_on:
      - elastic
      - db
    ports:
      - 14000:14000
    expose:
      - 14000/tcp
    volumes:
      - bcdshare:/etc/bcd
    links:
      - "flextesa:sandbox"
      - "ipfs:localipfs"
    logging: *bcd-logging

  indexer:
    restart: always
    image: bakingbad/bcdhub-indexer:4.0
    environment:
      - BCD_ENV=sandbox
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SANDBOX_NODE_URI=http://sandbox:20000
      - SANDBOX_IPFS_GATEWAY=http://localipfs:8080
    depends_on:
      - db
      - metrics
    links:
      - "flextesa:sandbox"
      - "ipfs:localipfs"
    volumes:
      - bcdshare:/etc/bcd
    logging: *bcd-logging

  metrics:
    restart: always
    image: bakingbad/bcdhub-metrics:4.0
    environment:
      - BCD_ENV=sandbox
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SANDBOX_NODE_URI=http://sandbox:20000
      - SANDBOX_IPFS_GATEWAY=http://localipfs:8080
    depends_on:
      - elastic
      - db
    links:
      - "flextesa:sandbox"
      - "ipfs:localipfs"
    volumes:
      - bcdshare:/etc/bcd
    logging: *bcd-logging

  flextesa:
    restart: always
    image: tqtezos/flextesa:20211119   #20211119 with hangzhou # 20210602 granada
    command: hangzbox start
    environment:
      - block_time=2
      - flextesa_node_cors_origin=*
    ports:
      - "20000:20000"
    expose:
      - 20000/tcp
    logging: *bcd-logging

  gui:
    container_name: sandbox-gui
    restart: always
    image: bakingbad/bcdhub-gui:4.0
    depends_on:
      - api
    ports:
      - 127.0.0.1:8000:80
    logging: *bcd-logging

  #graphql:
  #  restart: always
  #  image: tezoslive/taas-graphql
  #  depends_on:
  #    - flextesa
  #  environment:
  #    - TEZOS_NODE=http://sandbox:20000
  #  links:
  #    - "flextesa:sandbox"
  #  ports:
  #    - "3000:3000"
  #  logging: *bcd-logging

  ipfs:
    container_name: ipfs-node
    restart: always
    image: ipfs/go-ipfs:latest
    #bootstrap rm --all
    #command: bootstrap add /ip4/127.0.0.1/tcp/4001/ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc
    environment:
      #- IPFS_SWARM_KEY=/key/swarm/psk/1.0.0/\n/base16/\n925e93e58f6cb4aa7a5660e5166a3081f84d40a6888f70d49fdbc68f0f10362a
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./ipfsdata:/ipfsdata
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "5001:5001"
      - "8080:8080"
      - "8081:8081"
    expose:
      - 4001/tcp
      - 4001/udp
      - 5001/tcp
      - 8080/tcp
      - 8081/tcp
    logging: *bcd-logging

volumes:
  esdata:
  bcdshare:
  db:
    driver: local